
// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>
using System;
using System.Globalization;
using WithFormat;


public static class CultureExtentions {
			public static CurrencyCultureFormatBuilder ArabicSaudiArabiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ar-SA");
	}
			public static CurrencyCultureFormatBuilder BulgarianBulgariaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "bg-BG");
	}
			public static CurrencyCultureFormatBuilder CatalanCatalanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ca-ES");
	}
			public static CurrencyCultureFormatBuilder ChineseTraditionalTaiwanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "zh-TW");
	}
			public static CurrencyCultureFormatBuilder CzechCzechRepublicCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "cs-CZ");
	}
			public static CurrencyCultureFormatBuilder DanishDenmarkCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "da-DK");
	}
			public static CurrencyCultureFormatBuilder GermanGermanyCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "de-DE");
	}
			public static CurrencyCultureFormatBuilder GreekGreeceCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "el-GR");
	}
			public static CurrencyCultureFormatBuilder EnglishUnitedStatesCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "en-US");
	}
			public static CurrencyCultureFormatBuilder FinnishFinlandCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "fi-FI");
	}
			public static CurrencyCultureFormatBuilder FrenchFranceCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "fr-FR");
	}
			public static CurrencyCultureFormatBuilder HebrewIsraelCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "he-IL");
	}
			public static CurrencyCultureFormatBuilder HungarianHungaryCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "hu-HU");
	}
			public static CurrencyCultureFormatBuilder IcelandicIcelandCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "is-IS");
	}
			public static CurrencyCultureFormatBuilder ItalianItalyCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "it-IT");
	}
			public static CurrencyCultureFormatBuilder JapaneseJapanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ja-JP");
	}
			public static CurrencyCultureFormatBuilder KoreanKoreaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ko-KR");
	}
			public static CurrencyCultureFormatBuilder DutchNetherlandsCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "nl-NL");
	}
			public static CurrencyCultureFormatBuilder NorwegianBokmålNorwayCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "nb-NO");
	}
			public static CurrencyCultureFormatBuilder PolishPolandCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "pl-PL");
	}
			public static CurrencyCultureFormatBuilder PortugueseBrazilCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "pt-BR");
	}
			public static CurrencyCultureFormatBuilder RomanshSwitzerlandCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "rm-CH");
	}
			public static CurrencyCultureFormatBuilder RomanianRomaniaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ro-RO");
	}
			public static CurrencyCultureFormatBuilder RussianRussiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ru-RU");
	}
			public static CurrencyCultureFormatBuilder CroatianCroatiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "hr-HR");
	}
			public static CurrencyCultureFormatBuilder SlovakSlovakiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sk-SK");
	}
			public static CurrencyCultureFormatBuilder AlbanianAlbaniaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sq-AL");
	}
			public static CurrencyCultureFormatBuilder SwedishSwedenCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sv-SE");
	}
			public static CurrencyCultureFormatBuilder ThaiThailandCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "th-TH");
	}
			public static CurrencyCultureFormatBuilder TurkishTurkeyCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "tr-TR");
	}
			public static CurrencyCultureFormatBuilder UrduIslamicRepublicofPakistanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ur-PK");
	}
			public static CurrencyCultureFormatBuilder IndonesianIndonesiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "id-ID");
	}
			public static CurrencyCultureFormatBuilder UkrainianUkraineCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "uk-UA");
	}
			public static CurrencyCultureFormatBuilder BelarusianBelarusCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "be-BY");
	}
			public static CurrencyCultureFormatBuilder SlovenianSloveniaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sl-SI");
	}
			public static CurrencyCultureFormatBuilder EstonianEstoniaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "et-EE");
	}
			public static CurrencyCultureFormatBuilder LatvianLatviaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "lv-LV");
	}
			public static CurrencyCultureFormatBuilder LithuanianLithuaniaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "lt-LT");
	}
			public static CurrencyCultureFormatBuilder TajikCyrillicTajikistanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "tg-Cyrl-TJ");
	}
			public static CurrencyCultureFormatBuilder PersianCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "fa-IR");
	}
			public static CurrencyCultureFormatBuilder VietnameseVietnamCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "vi-VN");
	}
			public static CurrencyCultureFormatBuilder ArmenianArmeniaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "hy-AM");
	}
			public static CurrencyCultureFormatBuilder AzeriLatinAzerbaijanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "az-Latn-AZ");
	}
			public static CurrencyCultureFormatBuilder BasqueBasqueCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "eu-ES");
	}
			public static CurrencyCultureFormatBuilder UpperSorbianGermanyCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "hsb-DE");
	}
			public static CurrencyCultureFormatBuilder MacedonianFormerYugoslavRepublicofMacedoniaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "mk-MK");
	}
			public static CurrencyCultureFormatBuilder SetswanaSouthAfricaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "tn-ZA");
	}
			public static CurrencyCultureFormatBuilder isiXhosaSouthAfricaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "xh-ZA");
	}
			public static CurrencyCultureFormatBuilder isiZuluSouthAfricaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "zu-ZA");
	}
			public static CurrencyCultureFormatBuilder AfrikaansSouthAfricaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "af-ZA");
	}
			public static CurrencyCultureFormatBuilder GeorgianGeorgiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ka-GE");
	}
			public static CurrencyCultureFormatBuilder FaroeseFaroeIslandsCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "fo-FO");
	}
			public static CurrencyCultureFormatBuilder HindiIndiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "hi-IN");
	}
			public static CurrencyCultureFormatBuilder MalteseMaltaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "mt-MT");
	}
			public static CurrencyCultureFormatBuilder SamiNorthernNorwayCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "se-NO");
	}
			public static CurrencyCultureFormatBuilder MalayMalaysiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ms-MY");
	}
			public static CurrencyCultureFormatBuilder KazakhKazakhstanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "kk-KZ");
	}
			public static CurrencyCultureFormatBuilder KyrgyzKyrgyzstanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ky-KG");
	}
			public static CurrencyCultureFormatBuilder KiswahiliKenyaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sw-KE");
	}
			public static CurrencyCultureFormatBuilder TurkmenTurkmenistanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "tk-TM");
	}
			public static CurrencyCultureFormatBuilder UzbekLatinUzbekistanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "uz-Latn-UZ");
	}
			public static CurrencyCultureFormatBuilder TatarRussiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "tt-RU");
	}
			public static CurrencyCultureFormatBuilder BengaliIndiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "bn-IN");
	}
			public static CurrencyCultureFormatBuilder PunjabiIndiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "pa-IN");
	}
			public static CurrencyCultureFormatBuilder GujaratiIndiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "gu-IN");
	}
			public static CurrencyCultureFormatBuilder OriyaIndiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "or-IN");
	}
			public static CurrencyCultureFormatBuilder TamilIndiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ta-IN");
	}
			public static CurrencyCultureFormatBuilder TeluguIndiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "te-IN");
	}
			public static CurrencyCultureFormatBuilder KannadaIndiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "kn-IN");
	}
			public static CurrencyCultureFormatBuilder MalayalamIndiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ml-IN");
	}
			public static CurrencyCultureFormatBuilder AssameseIndiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "as-IN");
	}
			public static CurrencyCultureFormatBuilder MarathiIndiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "mr-IN");
	}
			public static CurrencyCultureFormatBuilder SanskritIndiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sa-IN");
	}
			public static CurrencyCultureFormatBuilder MongolianCyrillicMongoliaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "mn-MN");
	}
			public static CurrencyCultureFormatBuilder TibetanPRCCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "bo-CN");
	}
			public static CurrencyCultureFormatBuilder WelshUnitedKingdomCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "cy-GB");
	}
			public static CurrencyCultureFormatBuilder KhmerCambodiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "km-KH");
	}
			public static CurrencyCultureFormatBuilder LaoLaoPDRCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "lo-LA");
	}
			public static CurrencyCultureFormatBuilder GalicianGalicianCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "gl-ES");
	}
			public static CurrencyCultureFormatBuilder KonkaniIndiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "kok-IN");
	}
			public static CurrencyCultureFormatBuilder SyriacSyriaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "syr-SY");
	}
			public static CurrencyCultureFormatBuilder SinhalaSriLankaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "si-LK");
	}
			public static CurrencyCultureFormatBuilder CherokeeCherokeeCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "chr-Cher-US");
	}
			public static CurrencyCultureFormatBuilder InuktitutSyllabicsCanadaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "iu-Cans-CA");
	}
			public static CurrencyCultureFormatBuilder AmharicEthiopiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "am-ET");
	}
			public static CurrencyCultureFormatBuilder NepaliNepalCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ne-NP");
	}
			public static CurrencyCultureFormatBuilder FrisianNetherlandsCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "fy-NL");
	}
			public static CurrencyCultureFormatBuilder PashtoAfghanistanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ps-AF");
	}
			public static CurrencyCultureFormatBuilder FilipinoPhilippinesCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "fil-PH");
	}
			public static CurrencyCultureFormatBuilder DivehiMaldivesCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "dv-MV");
	}
			public static CurrencyCultureFormatBuilder HausaLatinNigeriaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ha-Latn-NG");
	}
			public static CurrencyCultureFormatBuilder YorubaNigeriaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "yo-NG");
	}
			public static CurrencyCultureFormatBuilder QuechuaBoliviaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "quz-BO");
	}
			public static CurrencyCultureFormatBuilder SesothosaLeboaSouthAfricaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "nso-ZA");
	}
			public static CurrencyCultureFormatBuilder BashkirRussiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ba-RU");
	}
			public static CurrencyCultureFormatBuilder LuxembourgishLuxembourgCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "lb-LU");
	}
			public static CurrencyCultureFormatBuilder GreenlandicGreenlandCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "kl-GL");
	}
			public static CurrencyCultureFormatBuilder IgboNigeriaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ig-NG");
	}
			public static CurrencyCultureFormatBuilder TigrinyaEthiopiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ti-ET");
	}
			public static CurrencyCultureFormatBuilder HawaiianUnitedStatesCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "haw-US");
	}
			public static CurrencyCultureFormatBuilder YiPRCCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ii-CN");
	}
			public static CurrencyCultureFormatBuilder MapudungunChileCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "arn-CL");
	}
			public static CurrencyCultureFormatBuilder MohawkMohawkCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "moh-CA");
	}
			public static CurrencyCultureFormatBuilder BretonFranceCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "br-FR");
	}
			public static CurrencyCultureFormatBuilder UyghurPRCCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ug-CN");
	}
			public static CurrencyCultureFormatBuilder MaoriNewZealandCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "mi-NZ");
	}
			public static CurrencyCultureFormatBuilder OccitanFranceCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "oc-FR");
	}
			public static CurrencyCultureFormatBuilder CorsicanFranceCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "co-FR");
	}
			public static CurrencyCultureFormatBuilder AlsatianFranceCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "gsw-FR");
	}
			public static CurrencyCultureFormatBuilder SakhaRussiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sah-RU");
	}
			public static CurrencyCultureFormatBuilder KicheGuatemalaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "qut-GT");
	}
			public static CurrencyCultureFormatBuilder KinyarwandaRwandaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "rw-RW");
	}
			public static CurrencyCultureFormatBuilder WolofSenegalCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "wo-SN");
	}
			public static CurrencyCultureFormatBuilder DariAfghanistanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "prs-AF");
	}
			public static CurrencyCultureFormatBuilder ScottishGaelicUnitedKingdomCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "gd-GB");
	}
			public static CurrencyCultureFormatBuilder CentralKurdishIraqCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ku-Arab-IQ");
	}
			public static CurrencyCultureFormatBuilder ArabicIraqCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ar-IQ");
	}
			public static CurrencyCultureFormatBuilder ValencianSpainCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ca-ES-valencia");
	}
			public static CurrencyCultureFormatBuilder ChineseSimplifiedPRCCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "zh-CN");
	}
			public static CurrencyCultureFormatBuilder GermanSwitzerlandCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "de-CH");
	}
			public static CurrencyCultureFormatBuilder EnglishUnitedKingdomCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "en-GB");
	}
			public static CurrencyCultureFormatBuilder SpanishMexicoCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-MX");
	}
			public static CurrencyCultureFormatBuilder FrenchBelgiumCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "fr-BE");
	}
			public static CurrencyCultureFormatBuilder ItalianSwitzerlandCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "it-CH");
	}
			public static CurrencyCultureFormatBuilder DutchBelgiumCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "nl-BE");
	}
			public static CurrencyCultureFormatBuilder NorwegianNynorskNorwayCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "nn-NO");
	}
			public static CurrencyCultureFormatBuilder PortuguesePortugalCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "pt-PT");
	}
			public static CurrencyCultureFormatBuilder SerbianLatinSerbiaandMontenegroFormerCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sr-Latn-CS");
	}
			public static CurrencyCultureFormatBuilder SwedishFinlandCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sv-FI");
	}
			public static CurrencyCultureFormatBuilder AzeriCyrillicAzerbaijanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "az-Cyrl-AZ");
	}
			public static CurrencyCultureFormatBuilder LowerSorbianGermanyCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "dsb-DE");
	}
			public static CurrencyCultureFormatBuilder SetswanaBotswanaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "tn-BW");
	}
			public static CurrencyCultureFormatBuilder SamiNorthernSwedenCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "se-SE");
	}
			public static CurrencyCultureFormatBuilder IrishIrelandCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ga-IE");
	}
			public static CurrencyCultureFormatBuilder MalayBruneiDarussalamCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ms-BN");
	}
			public static CurrencyCultureFormatBuilder UzbekCyrillicUzbekistanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "uz-Cyrl-UZ");
	}
			public static CurrencyCultureFormatBuilder BengaliBangladeshCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "bn-BD");
	}
			public static CurrencyCultureFormatBuilder PunjabiIslamicRepublicofPakistanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "pa-Arab-PK");
	}
			public static CurrencyCultureFormatBuilder TamilSriLankaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ta-LK");
	}
			public static CurrencyCultureFormatBuilder MongolianTraditionalMongolianPRCCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "mn-Mong-CN");
	}
			public static CurrencyCultureFormatBuilder SindhiIslamicRepublicofPakistanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sd-Arab-PK");
	}
			public static CurrencyCultureFormatBuilder InuktitutLatinCanadaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "iu-Latn-CA");
	}
			public static CurrencyCultureFormatBuilder TamazightLatinAlgeriaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "tzm-Latn-DZ");
	}
			public static CurrencyCultureFormatBuilder FulahLatinSenegalCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ff-Latn-SN");
	}
			public static CurrencyCultureFormatBuilder QuechuaEcuadorCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "quz-EC");
	}
			public static CurrencyCultureFormatBuilder TigrinyaEritreaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ti-ER");
	}
			public static CurrencyCultureFormatBuilder ArabicEgyptCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ar-EG");
	}
			public static CurrencyCultureFormatBuilder ChineseTraditionalHongKongSARCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "zh-HK");
	}
			public static CurrencyCultureFormatBuilder GermanAustriaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "de-AT");
	}
			public static CurrencyCultureFormatBuilder EnglishAustraliaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "en-AU");
	}
			public static CurrencyCultureFormatBuilder SpanishSpainCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-ES");
	}
			public static CurrencyCultureFormatBuilder FrenchCanadaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "fr-CA");
	}
			public static CurrencyCultureFormatBuilder SerbianCyrillicSerbiaandMontenegroFormerCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sr-Cyrl-CS");
	}
			public static CurrencyCultureFormatBuilder SamiNorthernFinlandCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "se-FI");
	}
			public static CurrencyCultureFormatBuilder QuechuaPeruCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "quz-PE");
	}
			public static CurrencyCultureFormatBuilder ArabicLibyaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ar-LY");
	}
			public static CurrencyCultureFormatBuilder ChineseSimplifiedSingaporeCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "zh-SG");
	}
			public static CurrencyCultureFormatBuilder GermanLuxembourgCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "de-LU");
	}
			public static CurrencyCultureFormatBuilder EnglishCanadaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "en-CA");
	}
			public static CurrencyCultureFormatBuilder SpanishGuatemalaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-GT");
	}
			public static CurrencyCultureFormatBuilder FrenchSwitzerlandCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "fr-CH");
	}
			public static CurrencyCultureFormatBuilder CroatianLatinBosniaandHerzegovinaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "hr-BA");
	}
			public static CurrencyCultureFormatBuilder SamiLuleNorwayCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "smj-NO");
	}
			public static CurrencyCultureFormatBuilder CentralAtlasTamazightTifinaghMoroccoCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "tzm-Tfng-MA");
	}
			public static CurrencyCultureFormatBuilder ArabicAlgeriaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ar-DZ");
	}
			public static CurrencyCultureFormatBuilder ChineseTraditionalMacaoSARCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "zh-MO");
	}
			public static CurrencyCultureFormatBuilder GermanLiechtensteinCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "de-LI");
	}
			public static CurrencyCultureFormatBuilder EnglishNewZealandCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "en-NZ");
	}
			public static CurrencyCultureFormatBuilder SpanishCostaRicaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-CR");
	}
			public static CurrencyCultureFormatBuilder FrenchLuxembourgCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "fr-LU");
	}
			public static CurrencyCultureFormatBuilder BosnianLatinBosniaandHerzegovinaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "bs-Latn-BA");
	}
			public static CurrencyCultureFormatBuilder SamiLuleSwedenCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "smj-SE");
	}
			public static CurrencyCultureFormatBuilder ArabicMoroccoCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ar-MA");
	}
			public static CurrencyCultureFormatBuilder EnglishIrelandCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "en-IE");
	}
			public static CurrencyCultureFormatBuilder SpanishPanamaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-PA");
	}
			public static CurrencyCultureFormatBuilder FrenchMonacoCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "fr-MC");
	}
			public static CurrencyCultureFormatBuilder SerbianLatinBosniaandHerzegovinaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sr-Latn-BA");
	}
			public static CurrencyCultureFormatBuilder SamiSouthernNorwayCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sma-NO");
	}
			public static CurrencyCultureFormatBuilder ArabicTunisiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ar-TN");
	}
			public static CurrencyCultureFormatBuilder EnglishSouthAfricaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "en-ZA");
	}
			public static CurrencyCultureFormatBuilder SpanishDominicanRepublicCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-DO");
	}
			public static CurrencyCultureFormatBuilder SerbianCyrillicBosniaandHerzegovinaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sr-Cyrl-BA");
	}
			public static CurrencyCultureFormatBuilder SamiSouthernSwedenCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sma-SE");
	}
			public static CurrencyCultureFormatBuilder ArabicOmanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ar-OM");
	}
			public static CurrencyCultureFormatBuilder EnglishJamaicaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "en-JM");
	}
			public static CurrencyCultureFormatBuilder SpanishBolivarianRepublicofVenezuelaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-VE");
	}
			public static CurrencyCultureFormatBuilder BosnianCyrillicBosniaandHerzegovinaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "bs-Cyrl-BA");
	}
			public static CurrencyCultureFormatBuilder SamiSkoltFinlandCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sms-FI");
	}
			public static CurrencyCultureFormatBuilder ArabicYemenCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ar-YE");
	}
			public static CurrencyCultureFormatBuilder EnglishCaribbeanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "en-029");
	}
			public static CurrencyCultureFormatBuilder SpanishColombiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-CO");
	}
			public static CurrencyCultureFormatBuilder SerbianLatinSerbiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sr-Latn-RS");
	}
			public static CurrencyCultureFormatBuilder SamiInariFinlandCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "smn-FI");
	}
			public static CurrencyCultureFormatBuilder ArabicSyriaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ar-SY");
	}
			public static CurrencyCultureFormatBuilder EnglishBelizeCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "en-BZ");
	}
			public static CurrencyCultureFormatBuilder SpanishPeruCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-PE");
	}
			public static CurrencyCultureFormatBuilder SerbianCyrillicSerbiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sr-Cyrl-RS");
	}
			public static CurrencyCultureFormatBuilder ArabicJordanCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ar-JO");
	}
			public static CurrencyCultureFormatBuilder EnglishTrinidadandTobagoCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "en-TT");
	}
			public static CurrencyCultureFormatBuilder SpanishArgentinaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-AR");
	}
			public static CurrencyCultureFormatBuilder SerbianLatinMontenegroCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sr-Latn-ME");
	}
			public static CurrencyCultureFormatBuilder ArabicLebanonCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ar-LB");
	}
			public static CurrencyCultureFormatBuilder EnglishZimbabweCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "en-ZW");
	}
			public static CurrencyCultureFormatBuilder SpanishEcuadorCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-EC");
	}
			public static CurrencyCultureFormatBuilder SerbianCyrillicMontenegroCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "sr-Cyrl-ME");
	}
			public static CurrencyCultureFormatBuilder ArabicKuwaitCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ar-KW");
	}
			public static CurrencyCultureFormatBuilder EnglishRepublicofthePhilippinesCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "en-PH");
	}
			public static CurrencyCultureFormatBuilder SpanishChileCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-CL");
	}
			public static CurrencyCultureFormatBuilder ArabicUAECulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ar-AE");
	}
			public static CurrencyCultureFormatBuilder SpanishUruguayCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-UY");
	}
			public static CurrencyCultureFormatBuilder ArabicBahrainCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ar-BH");
	}
			public static CurrencyCultureFormatBuilder SpanishParaguayCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-PY");
	}
			public static CurrencyCultureFormatBuilder ArabicQatarCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "ar-QA");
	}
			public static CurrencyCultureFormatBuilder EnglishIndiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "en-IN");
	}
			public static CurrencyCultureFormatBuilder SpanishBoliviaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-BO");
	}
			public static CurrencyCultureFormatBuilder EnglishMalaysiaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "en-MY");
	}
			public static CurrencyCultureFormatBuilder SpanishElSalvadorCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-SV");
	}
			public static CurrencyCultureFormatBuilder EnglishSingaporeCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "en-SG");
	}
			public static CurrencyCultureFormatBuilder SpanishHondurasCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-HN");
	}
			public static CurrencyCultureFormatBuilder SpanishNicaraguaCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-NI");
	}
			public static CurrencyCultureFormatBuilder SpanishPuertoRicoCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-PR");
	}
			public static CurrencyCultureFormatBuilder SpanishUnitedStatesCulture(this IntegerFormatBuilder builder)
	{
		return new CurrencyCultureFormatBuilder(builder, "es-US");
	}
	}