
// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>
using System;
using System.Globalization;
using WithFormat;


public class ArabicSaudiArabiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ar-SA");
    }
}
public class BulgarianBulgariaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("bg-BG");
    }
}
public class CatalanCatalanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ca-ES");
    }
}
public class ChineseTraditionalTaiwanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("zh-TW");
    }
}
public class CzechCzechRepublicCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("cs-CZ");
    }
}
public class DanishDenmarkCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("da-DK");
    }
}
public class GermanGermanyCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("de-DE");
    }
}
public class GreekGreeceCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("el-GR");
    }
}
public class EnglishUnitedStatesCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("en-US");
    }
}
public class FinnishFinlandCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("fi-FI");
    }
}
public class FrenchFranceCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("fr-FR");
    }
}
public class HebrewIsraelCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("he-IL");
    }
}
public class HungarianHungaryCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("hu-HU");
    }
}
public class IcelandicIcelandCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("is-IS");
    }
}
public class ItalianItalyCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("it-IT");
    }
}
public class JapaneseJapanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ja-JP");
    }
}
public class KoreanKoreaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ko-KR");
    }
}
public class DutchNetherlandsCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("nl-NL");
    }
}
public class NorwegianBokmålNorwayCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("nb-NO");
    }
}
public class PolishPolandCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("pl-PL");
    }
}
public class PortugueseBrazilCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("pt-BR");
    }
}
public class RomanshSwitzerlandCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("rm-CH");
    }
}
public class RomanianRomaniaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ro-RO");
    }
}
public class RussianRussiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ru-RU");
    }
}
public class CroatianCroatiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("hr-HR");
    }
}
public class SlovakSlovakiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sk-SK");
    }
}
public class AlbanianAlbaniaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sq-AL");
    }
}
public class SwedishSwedenCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sv-SE");
    }
}
public class ThaiThailandCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("th-TH");
    }
}
public class TurkishTurkeyCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("tr-TR");
    }
}
public class UrduIslamicRepublicofPakistanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ur-PK");
    }
}
public class IndonesianIndonesiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("id-ID");
    }
}
public class UkrainianUkraineCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("uk-UA");
    }
}
public class BelarusianBelarusCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("be-BY");
    }
}
public class SlovenianSloveniaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sl-SI");
    }
}
public class EstonianEstoniaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("et-EE");
    }
}
public class LatvianLatviaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("lv-LV");
    }
}
public class LithuanianLithuaniaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("lt-LT");
    }
}
public class TajikCyrillicTajikistanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("tg-Cyrl-TJ");
    }
}
public class PersianCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("fa-IR");
    }
}
public class VietnameseVietnamCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("vi-VN");
    }
}
public class ArmenianArmeniaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("hy-AM");
    }
}
public class AzeriLatinAzerbaijanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("az-Latn-AZ");
    }
}
public class BasqueBasqueCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("eu-ES");
    }
}
public class UpperSorbianGermanyCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("hsb-DE");
    }
}
public class MacedonianFormerYugoslavRepublicofMacedoniaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("mk-MK");
    }
}
public class SetswanaSouthAfricaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("tn-ZA");
    }
}
public class isiXhosaSouthAfricaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("xh-ZA");
    }
}
public class isiZuluSouthAfricaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("zu-ZA");
    }
}
public class AfrikaansSouthAfricaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("af-ZA");
    }
}
public class GeorgianGeorgiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ka-GE");
    }
}
public class FaroeseFaroeIslandsCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("fo-FO");
    }
}
public class HindiIndiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("hi-IN");
    }
}
public class MalteseMaltaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("mt-MT");
    }
}
public class SamiNorthernNorwayCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("se-NO");
    }
}
public class MalayMalaysiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ms-MY");
    }
}
public class KazakhKazakhstanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("kk-KZ");
    }
}
public class KyrgyzKyrgyzstanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ky-KG");
    }
}
public class KiswahiliKenyaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sw-KE");
    }
}
public class TurkmenTurkmenistanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("tk-TM");
    }
}
public class UzbekLatinUzbekistanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("uz-Latn-UZ");
    }
}
public class TatarRussiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("tt-RU");
    }
}
public class BengaliIndiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("bn-IN");
    }
}
public class PunjabiIndiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("pa-IN");
    }
}
public class GujaratiIndiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("gu-IN");
    }
}
public class OriyaIndiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("or-IN");
    }
}
public class TamilIndiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ta-IN");
    }
}
public class TeluguIndiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("te-IN");
    }
}
public class KannadaIndiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("kn-IN");
    }
}
public class MalayalamIndiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ml-IN");
    }
}
public class AssameseIndiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("as-IN");
    }
}
public class MarathiIndiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("mr-IN");
    }
}
public class SanskritIndiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sa-IN");
    }
}
public class MongolianCyrillicMongoliaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("mn-MN");
    }
}
public class TibetanPRCCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("bo-CN");
    }
}
public class WelshUnitedKingdomCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("cy-GB");
    }
}
public class KhmerCambodiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("km-KH");
    }
}
public class LaoLaoPDRCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("lo-LA");
    }
}
public class GalicianGalicianCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("gl-ES");
    }
}
public class KonkaniIndiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("kok-IN");
    }
}
public class SyriacSyriaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("syr-SY");
    }
}
public class SinhalaSriLankaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("si-LK");
    }
}
public class CherokeeCherokeeCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("chr-Cher-US");
    }
}
public class InuktitutSyllabicsCanadaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("iu-Cans-CA");
    }
}
public class AmharicEthiopiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("am-ET");
    }
}
public class NepaliNepalCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ne-NP");
    }
}
public class FrisianNetherlandsCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("fy-NL");
    }
}
public class PashtoAfghanistanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ps-AF");
    }
}
public class FilipinoPhilippinesCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("fil-PH");
    }
}
public class DivehiMaldivesCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("dv-MV");
    }
}
public class HausaLatinNigeriaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ha-Latn-NG");
    }
}
public class YorubaNigeriaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("yo-NG");
    }
}
public class QuechuaBoliviaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("quz-BO");
    }
}
public class SesothosaLeboaSouthAfricaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("nso-ZA");
    }
}
public class BashkirRussiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ba-RU");
    }
}
public class LuxembourgishLuxembourgCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("lb-LU");
    }
}
public class GreenlandicGreenlandCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("kl-GL");
    }
}
public class IgboNigeriaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ig-NG");
    }
}
public class TigrinyaEthiopiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ti-ET");
    }
}
public class HawaiianUnitedStatesCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("haw-US");
    }
}
public class YiPRCCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ii-CN");
    }
}
public class MapudungunChileCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("arn-CL");
    }
}
public class MohawkMohawkCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("moh-CA");
    }
}
public class BretonFranceCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("br-FR");
    }
}
public class UyghurPRCCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ug-CN");
    }
}
public class MaoriNewZealandCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("mi-NZ");
    }
}
public class OccitanFranceCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("oc-FR");
    }
}
public class CorsicanFranceCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("co-FR");
    }
}
public class AlsatianFranceCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("gsw-FR");
    }
}
public class SakhaRussiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sah-RU");
    }
}
public class KicheGuatemalaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("qut-GT");
    }
}
public class KinyarwandaRwandaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("rw-RW");
    }
}
public class WolofSenegalCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("wo-SN");
    }
}
public class DariAfghanistanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("prs-AF");
    }
}
public class ScottishGaelicUnitedKingdomCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("gd-GB");
    }
}
public class CentralKurdishIraqCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ku-Arab-IQ");
    }
}
public class ArabicIraqCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ar-IQ");
    }
}
public class ValencianSpainCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ca-ES-valencia");
    }
}
public class ChineseSimplifiedPRCCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("zh-CN");
    }
}
public class GermanSwitzerlandCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("de-CH");
    }
}
public class EnglishUnitedKingdomCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("en-GB");
    }
}
public class SpanishMexicoCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-MX");
    }
}
public class FrenchBelgiumCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("fr-BE");
    }
}
public class ItalianSwitzerlandCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("it-CH");
    }
}
public class DutchBelgiumCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("nl-BE");
    }
}
public class NorwegianNynorskNorwayCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("nn-NO");
    }
}
public class PortuguesePortugalCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("pt-PT");
    }
}
public class SerbianLatinSerbiaandMontenegroFormerCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sr-Latn-CS");
    }
}
public class SwedishFinlandCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sv-FI");
    }
}
public class AzeriCyrillicAzerbaijanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("az-Cyrl-AZ");
    }
}
public class LowerSorbianGermanyCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("dsb-DE");
    }
}
public class SetswanaBotswanaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("tn-BW");
    }
}
public class SamiNorthernSwedenCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("se-SE");
    }
}
public class IrishIrelandCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ga-IE");
    }
}
public class MalayBruneiDarussalamCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ms-BN");
    }
}
public class UzbekCyrillicUzbekistanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("uz-Cyrl-UZ");
    }
}
public class BengaliBangladeshCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("bn-BD");
    }
}
public class PunjabiIslamicRepublicofPakistanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("pa-Arab-PK");
    }
}
public class TamilSriLankaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ta-LK");
    }
}
public class MongolianTraditionalMongolianPRCCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("mn-Mong-CN");
    }
}
public class SindhiIslamicRepublicofPakistanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sd-Arab-PK");
    }
}
public class InuktitutLatinCanadaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("iu-Latn-CA");
    }
}
public class TamazightLatinAlgeriaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("tzm-Latn-DZ");
    }
}
public class FulahLatinSenegalCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ff-Latn-SN");
    }
}
public class QuechuaEcuadorCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("quz-EC");
    }
}
public class TigrinyaEritreaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ti-ER");
    }
}
public class ArabicEgyptCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ar-EG");
    }
}
public class ChineseTraditionalHongKongSARCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("zh-HK");
    }
}
public class GermanAustriaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("de-AT");
    }
}
public class EnglishAustraliaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("en-AU");
    }
}
public class SpanishSpainCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-ES");
    }
}
public class FrenchCanadaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("fr-CA");
    }
}
public class SerbianCyrillicSerbiaandMontenegroFormerCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sr-Cyrl-CS");
    }
}
public class SamiNorthernFinlandCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("se-FI");
    }
}
public class QuechuaPeruCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("quz-PE");
    }
}
public class ArabicLibyaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ar-LY");
    }
}
public class ChineseSimplifiedSingaporeCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("zh-SG");
    }
}
public class GermanLuxembourgCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("de-LU");
    }
}
public class EnglishCanadaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("en-CA");
    }
}
public class SpanishGuatemalaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-GT");
    }
}
public class FrenchSwitzerlandCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("fr-CH");
    }
}
public class CroatianLatinBosniaandHerzegovinaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("hr-BA");
    }
}
public class SamiLuleNorwayCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("smj-NO");
    }
}
public class CentralAtlasTamazightTifinaghMoroccoCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("tzm-Tfng-MA");
    }
}
public class ArabicAlgeriaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ar-DZ");
    }
}
public class ChineseTraditionalMacaoSARCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("zh-MO");
    }
}
public class GermanLiechtensteinCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("de-LI");
    }
}
public class EnglishNewZealandCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("en-NZ");
    }
}
public class SpanishCostaRicaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-CR");
    }
}
public class FrenchLuxembourgCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("fr-LU");
    }
}
public class BosnianLatinBosniaandHerzegovinaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("bs-Latn-BA");
    }
}
public class SamiLuleSwedenCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("smj-SE");
    }
}
public class ArabicMoroccoCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ar-MA");
    }
}
public class EnglishIrelandCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("en-IE");
    }
}
public class SpanishPanamaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-PA");
    }
}
public class FrenchMonacoCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("fr-MC");
    }
}
public class SerbianLatinBosniaandHerzegovinaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sr-Latn-BA");
    }
}
public class SamiSouthernNorwayCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sma-NO");
    }
}
public class ArabicTunisiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ar-TN");
    }
}
public class EnglishSouthAfricaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("en-ZA");
    }
}
public class SpanishDominicanRepublicCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-DO");
    }
}
public class SerbianCyrillicBosniaandHerzegovinaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sr-Cyrl-BA");
    }
}
public class SamiSouthernSwedenCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sma-SE");
    }
}
public class ArabicOmanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ar-OM");
    }
}
public class EnglishJamaicaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("en-JM");
    }
}
public class SpanishBolivarianRepublicofVenezuelaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-VE");
    }
}
public class BosnianCyrillicBosniaandHerzegovinaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("bs-Cyrl-BA");
    }
}
public class SamiSkoltFinlandCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sms-FI");
    }
}
public class ArabicYemenCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ar-YE");
    }
}
public class EnglishCaribbeanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("en-029");
    }
}
public class SpanishColombiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-CO");
    }
}
public class SerbianLatinSerbiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sr-Latn-RS");
    }
}
public class SamiInariFinlandCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("smn-FI");
    }
}
public class ArabicSyriaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ar-SY");
    }
}
public class EnglishBelizeCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("en-BZ");
    }
}
public class SpanishPeruCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-PE");
    }
}
public class SerbianCyrillicSerbiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sr-Cyrl-RS");
    }
}
public class ArabicJordanCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ar-JO");
    }
}
public class EnglishTrinidadandTobagoCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("en-TT");
    }
}
public class SpanishArgentinaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-AR");
    }
}
public class SerbianLatinMontenegroCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sr-Latn-ME");
    }
}
public class ArabicLebanonCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ar-LB");
    }
}
public class EnglishZimbabweCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("en-ZW");
    }
}
public class SpanishEcuadorCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-EC");
    }
}
public class SerbianCyrillicMontenegroCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("sr-Cyrl-ME");
    }
}
public class ArabicKuwaitCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ar-KW");
    }
}
public class EnglishRepublicofthePhilippinesCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("en-PH");
    }
}
public class SpanishChileCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-CL");
    }
}
public class ArabicUAECulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ar-AE");
    }
}
public class SpanishUruguayCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-UY");
    }
}
public class ArabicBahrainCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ar-BH");
    }
}
public class SpanishParaguayCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-PY");
    }
}
public class ArabicQatarCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("ar-QA");
    }
}
public class EnglishIndiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("en-IN");
    }
}
public class SpanishBoliviaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-BO");
    }
}
public class EnglishMalaysiaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("en-MY");
    }
}
public class SpanishElSalvadorCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-SV");
    }
}
public class EnglishSingaporeCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("en-SG");
    }
}
public class SpanishHondurasCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-HN");
    }
}
public class SpanishNicaraguaCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-NI");
    }
}
public class SpanishPuertoRicoCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-PR");
    }
}
public class SpanishUnitedStatesCulture : IFormatCulture {

    public CultureInfo Culture() {
        return CultureInfo.CreateSpecificCulture("es-US");
    }
}
