
// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>
using System.Globalization;

namespace WithFormat.Cultures
{
            public class AfrikaansSouthAfricaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("af-ZA");
        }

        public string GetCultureCode(){
            return "af-ZA";
        }
    }
            public class AmharicEthiopiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("am-ET");
        }

        public string GetCultureCode(){
            return "am-ET";
        }
    }
            public class ArabicUAECulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ar-AE");
        }

        public string GetCultureCode(){
            return "ar-AE";
        }
    }
            public class ArabicBahrainCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ar-BH");
        }

        public string GetCultureCode(){
            return "ar-BH";
        }
    }
            public class ArabicAlgeriaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ar-DZ");
        }

        public string GetCultureCode(){
            return "ar-DZ";
        }
    }
            public class ArabicEgyptCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ar-EG");
        }

        public string GetCultureCode(){
            return "ar-EG";
        }
    }
            public class ArabicIraqCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ar-IQ");
        }

        public string GetCultureCode(){
            return "ar-IQ";
        }
    }
            public class ArabicJordanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ar-JO");
        }

        public string GetCultureCode(){
            return "ar-JO";
        }
    }
            public class ArabicKuwaitCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ar-KW");
        }

        public string GetCultureCode(){
            return "ar-KW";
        }
    }
            public class ArabicLebanonCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ar-LB");
        }

        public string GetCultureCode(){
            return "ar-LB";
        }
    }
            public class ArabicLibyaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ar-LY");
        }

        public string GetCultureCode(){
            return "ar-LY";
        }
    }
            public class ArabicMoroccoCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ar-MA");
        }

        public string GetCultureCode(){
            return "ar-MA";
        }
    }
            public class ArabicOmanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ar-OM");
        }

        public string GetCultureCode(){
            return "ar-OM";
        }
    }
            public class ArabicQatarCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ar-QA");
        }

        public string GetCultureCode(){
            return "ar-QA";
        }
    }
            public class ArabicSaudiArabiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ar-SA");
        }

        public string GetCultureCode(){
            return "ar-SA";
        }
    }
            public class ArabicSyriaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ar-SY");
        }

        public string GetCultureCode(){
            return "ar-SY";
        }
    }
            public class ArabicTunisiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ar-TN");
        }

        public string GetCultureCode(){
            return "ar-TN";
        }
    }
            public class ArabicYemenCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ar-YE");
        }

        public string GetCultureCode(){
            return "ar-YE";
        }
    }
            public class MapudungunChileCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("arn-CL");
        }

        public string GetCultureCode(){
            return "arn-CL";
        }
    }
            public class AssameseIndiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("as-IN");
        }

        public string GetCultureCode(){
            return "as-IN";
        }
    }
            public class AzerbaijaniCyrillicAzerbaijanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("az-Cyrl-AZ");
        }

        public string GetCultureCode(){
            return "az-Cyrl-AZ";
        }
    }
            public class AzerbaijaniLatinAzerbaijanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("az-Latn-AZ");
        }

        public string GetCultureCode(){
            return "az-Latn-AZ";
        }
    }
            public class BashkirRussiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ba-RU");
        }

        public string GetCultureCode(){
            return "ba-RU";
        }
    }
            public class BelarusianBelarusCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("be-BY");
        }

        public string GetCultureCode(){
            return "be-BY";
        }
    }
            public class BulgarianBulgariaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("bg-BG");
        }

        public string GetCultureCode(){
            return "bg-BG";
        }
    }
            public class BanglaBangladeshCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("bn-BD");
        }

        public string GetCultureCode(){
            return "bn-BD";
        }
    }
            public class BanglaIndiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("bn-IN");
        }

        public string GetCultureCode(){
            return "bn-IN";
        }
    }
            public class TibetanChinaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("bo-CN");
        }

        public string GetCultureCode(){
            return "bo-CN";
        }
    }
            public class BretonFranceCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("br-FR");
        }

        public string GetCultureCode(){
            return "br-FR";
        }
    }
            public class BosnianCyrillicBosniaandHerzegovinaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("bs-Cyrl-BA");
        }

        public string GetCultureCode(){
            return "bs-Cyrl-BA";
        }
    }
            public class BosnianLatinBosniaandHerzegovinaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("bs-Latn-BA");
        }

        public string GetCultureCode(){
            return "bs-Latn-BA";
        }
    }
            public class CatalanCatalanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ca-ES");
        }

        public string GetCultureCode(){
            return "ca-ES";
        }
    }
            public class ValencianSpainCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ca-ES-valencia");
        }

        public string GetCultureCode(){
            return "ca-ES-valencia";
        }
    }
            public class CherokeeCherokeeCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("chr-Cher-US");
        }

        public string GetCultureCode(){
            return "chr-Cher-US";
        }
    }
            public class CorsicanFranceCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("co-FR");
        }

        public string GetCultureCode(){
            return "co-FR";
        }
    }
            public class CzechCzechRepublicCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("cs-CZ");
        }

        public string GetCultureCode(){
            return "cs-CZ";
        }
    }
            public class WelshUnitedKingdomCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("cy-GB");
        }

        public string GetCultureCode(){
            return "cy-GB";
        }
    }
            public class DanishDenmarkCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("da-DK");
        }

        public string GetCultureCode(){
            return "da-DK";
        }
    }
            public class GermanAustriaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("de-AT");
        }

        public string GetCultureCode(){
            return "de-AT";
        }
    }
            public class GermanSwitzerlandCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("de-CH");
        }

        public string GetCultureCode(){
            return "de-CH";
        }
    }
            public class GermanGermanyCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("de-DE");
        }

        public string GetCultureCode(){
            return "de-DE";
        }
    }
            public class GermanLiechtensteinCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("de-LI");
        }

        public string GetCultureCode(){
            return "de-LI";
        }
    }
            public class GermanLuxembourgCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("de-LU");
        }

        public string GetCultureCode(){
            return "de-LU";
        }
    }
            public class LowerSorbianGermanyCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("dsb-DE");
        }

        public string GetCultureCode(){
            return "dsb-DE";
        }
    }
            public class DivehiMaldivesCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("dv-MV");
        }

        public string GetCultureCode(){
            return "dv-MV";
        }
    }
            public class GreekGreeceCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("el-GR");
        }

        public string GetCultureCode(){
            return "el-GR";
        }
    }
            public class EnglishCaribbeanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("en-029");
        }

        public string GetCultureCode(){
            return "en-029";
        }
    }
            public class EnglishAustraliaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("en-AU");
        }

        public string GetCultureCode(){
            return "en-AU";
        }
    }
            public class EnglishBelizeCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("en-BZ");
        }

        public string GetCultureCode(){
            return "en-BZ";
        }
    }
            public class EnglishCanadaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("en-CA");
        }

        public string GetCultureCode(){
            return "en-CA";
        }
    }
            public class EnglishUnitedKingdomCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("en-GB");
        }

        public string GetCultureCode(){
            return "en-GB";
        }
    }
            public class EnglishHongKongCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("en-HK");
        }

        public string GetCultureCode(){
            return "en-HK";
        }
    }
            public class EnglishIrelandCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("en-IE");
        }

        public string GetCultureCode(){
            return "en-IE";
        }
    }
            public class EnglishIndiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("en-IN");
        }

        public string GetCultureCode(){
            return "en-IN";
        }
    }
            public class EnglishJamaicaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("en-JM");
        }

        public string GetCultureCode(){
            return "en-JM";
        }
    }
            public class EnglishMalaysiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("en-MY");
        }

        public string GetCultureCode(){
            return "en-MY";
        }
    }
            public class EnglishNewZealandCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("en-NZ");
        }

        public string GetCultureCode(){
            return "en-NZ";
        }
    }
            public class EnglishPhilippinesCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("en-PH");
        }

        public string GetCultureCode(){
            return "en-PH";
        }
    }
            public class EnglishSingaporeCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("en-SG");
        }

        public string GetCultureCode(){
            return "en-SG";
        }
    }
            public class EnglishTrinidadandTobagoCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("en-TT");
        }

        public string GetCultureCode(){
            return "en-TT";
        }
    }
            public class EnglishUnitedStatesCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("en-US");
        }

        public string GetCultureCode(){
            return "en-US";
        }
    }
            public class EnglishSouthAfricaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("en-ZA");
        }

        public string GetCultureCode(){
            return "en-ZA";
        }
    }
            public class EnglishZimbabweCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("en-ZW");
        }

        public string GetCultureCode(){
            return "en-ZW";
        }
    }
            public class SpanishLatinAmericaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-419");
        }

        public string GetCultureCode(){
            return "es-419";
        }
    }
            public class SpanishArgentinaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-AR");
        }

        public string GetCultureCode(){
            return "es-AR";
        }
    }
            public class SpanishBoliviaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-BO");
        }

        public string GetCultureCode(){
            return "es-BO";
        }
    }
            public class SpanishChileCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-CL");
        }

        public string GetCultureCode(){
            return "es-CL";
        }
    }
            public class SpanishColombiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-CO");
        }

        public string GetCultureCode(){
            return "es-CO";
        }
    }
            public class SpanishCostaRicaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-CR");
        }

        public string GetCultureCode(){
            return "es-CR";
        }
    }
            public class SpanishDominicanRepublicCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-DO");
        }

        public string GetCultureCode(){
            return "es-DO";
        }
    }
            public class SpanishEcuadorCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-EC");
        }

        public string GetCultureCode(){
            return "es-EC";
        }
    }
            public class SpanishSpainInternationalSortCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-ES");
        }

        public string GetCultureCode(){
            return "es-ES";
        }
    }
            public class SpanishGuatemalaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-GT");
        }

        public string GetCultureCode(){
            return "es-GT";
        }
    }
            public class SpanishHondurasCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-HN");
        }

        public string GetCultureCode(){
            return "es-HN";
        }
    }
            public class SpanishMexicoCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-MX");
        }

        public string GetCultureCode(){
            return "es-MX";
        }
    }
            public class SpanishNicaraguaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-NI");
        }

        public string GetCultureCode(){
            return "es-NI";
        }
    }
            public class SpanishPanamaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-PA");
        }

        public string GetCultureCode(){
            return "es-PA";
        }
    }
            public class SpanishPeruCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-PE");
        }

        public string GetCultureCode(){
            return "es-PE";
        }
    }
            public class SpanishPuertoRicoCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-PR");
        }

        public string GetCultureCode(){
            return "es-PR";
        }
    }
            public class SpanishParaguayCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-PY");
        }

        public string GetCultureCode(){
            return "es-PY";
        }
    }
            public class SpanishElSalvadorCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-SV");
        }

        public string GetCultureCode(){
            return "es-SV";
        }
    }
            public class SpanishUnitedStatesCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-US");
        }

        public string GetCultureCode(){
            return "es-US";
        }
    }
            public class SpanishUruguayCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-UY");
        }

        public string GetCultureCode(){
            return "es-UY";
        }
    }
            public class SpanishBolivarianRepublicofVenezuelaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("es-VE");
        }

        public string GetCultureCode(){
            return "es-VE";
        }
    }
            public class EstonianEstoniaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("et-EE");
        }

        public string GetCultureCode(){
            return "et-EE";
        }
    }
            public class BasqueBasqueCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("eu-ES");
        }

        public string GetCultureCode(){
            return "eu-ES";
        }
    }
            public class PersianCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fa-IR");
        }

        public string GetCultureCode(){
            return "fa-IR";
        }
    }
            public class FulahLatinSenegalCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ff-Latn-SN");
        }

        public string GetCultureCode(){
            return "ff-Latn-SN";
        }
    }
            public class FinnishFinlandCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fi-FI");
        }

        public string GetCultureCode(){
            return "fi-FI";
        }
    }
            public class FilipinoPhilippinesCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fil-PH");
        }

        public string GetCultureCode(){
            return "fil-PH";
        }
    }
            public class FaroeseFaroeIslandsCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fo-FO");
        }

        public string GetCultureCode(){
            return "fo-FO";
        }
    }
            public class FrenchBelgiumCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fr-BE");
        }

        public string GetCultureCode(){
            return "fr-BE";
        }
    }
            public class FrenchCanadaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fr-CA");
        }

        public string GetCultureCode(){
            return "fr-CA";
        }
    }
            public class FrenchCongoDRCCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fr-CD");
        }

        public string GetCultureCode(){
            return "fr-CD";
        }
    }
            public class FrenchSwitzerlandCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fr-CH");
        }

        public string GetCultureCode(){
            return "fr-CH";
        }
    }
            public class FrenchIvoryCoastCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fr-CI");
        }

        public string GetCultureCode(){
            return "fr-CI";
        }
    }
            public class FrenchCameroonCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fr-CM");
        }

        public string GetCultureCode(){
            return "fr-CM";
        }
    }
            public class FrenchFranceCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fr-FR");
        }

        public string GetCultureCode(){
            return "fr-FR";
        }
    }
            public class FrenchHaitiCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fr-HT");
        }

        public string GetCultureCode(){
            return "fr-HT";
        }
    }
            public class FrenchLuxembourgCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fr-LU");
        }

        public string GetCultureCode(){
            return "fr-LU";
        }
    }
            public class FrenchMoroccoCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fr-MA");
        }

        public string GetCultureCode(){
            return "fr-MA";
        }
    }
            public class FrenchMonacoCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fr-MC");
        }

        public string GetCultureCode(){
            return "fr-MC";
        }
    }
            public class FrenchMaliCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fr-ML");
        }

        public string GetCultureCode(){
            return "fr-ML";
        }
    }
            public class FrenchRéunionCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fr-RE");
        }

        public string GetCultureCode(){
            return "fr-RE";
        }
    }
            public class FrenchSenegalCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fr-SN");
        }

        public string GetCultureCode(){
            return "fr-SN";
        }
    }
            public class FrisianNetherlandsCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("fy-NL");
        }

        public string GetCultureCode(){
            return "fy-NL";
        }
    }
            public class IrishIrelandCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ga-IE");
        }

        public string GetCultureCode(){
            return "ga-IE";
        }
    }
            public class ScottishGaelicUnitedKingdomCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("gd-GB");
        }

        public string GetCultureCode(){
            return "gd-GB";
        }
    }
            public class GalicianGalicianCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("gl-ES");
        }

        public string GetCultureCode(){
            return "gl-ES";
        }
    }
            public class GuaraniParaguayCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("gn-PY");
        }

        public string GetCultureCode(){
            return "gn-PY";
        }
    }
            public class AlsatianFranceCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("gsw-FR");
        }

        public string GetCultureCode(){
            return "gsw-FR";
        }
    }
            public class GujaratiIndiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("gu-IN");
        }

        public string GetCultureCode(){
            return "gu-IN";
        }
    }
            public class HausaLatinNigeriaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ha-Latn-NG");
        }

        public string GetCultureCode(){
            return "ha-Latn-NG";
        }
    }
            public class HawaiianUnitedStatesCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("haw-US");
        }

        public string GetCultureCode(){
            return "haw-US";
        }
    }
            public class HebrewIsraelCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("he-IL");
        }

        public string GetCultureCode(){
            return "he-IL";
        }
    }
            public class HindiIndiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("hi-IN");
        }

        public string GetCultureCode(){
            return "hi-IN";
        }
    }
            public class CroatianLatinBosniaandHerzegovinaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("hr-BA");
        }

        public string GetCultureCode(){
            return "hr-BA";
        }
    }
            public class CroatianCroatiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("hr-HR");
        }

        public string GetCultureCode(){
            return "hr-HR";
        }
    }
            public class UpperSorbianGermanyCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("hsb-DE");
        }

        public string GetCultureCode(){
            return "hsb-DE";
        }
    }
            public class HungarianHungaryCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("hu-HU");
        }

        public string GetCultureCode(){
            return "hu-HU";
        }
    }
            public class ArmenianArmeniaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("hy-AM");
        }

        public string GetCultureCode(){
            return "hy-AM";
        }
    }
            public class IndonesianIndonesiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("id-ID");
        }

        public string GetCultureCode(){
            return "id-ID";
        }
    }
            public class IgboNigeriaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ig-NG");
        }

        public string GetCultureCode(){
            return "ig-NG";
        }
    }
            public class YiChinaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ii-CN");
        }

        public string GetCultureCode(){
            return "ii-CN";
        }
    }
            public class IcelandicIcelandCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("is-IS");
        }

        public string GetCultureCode(){
            return "is-IS";
        }
    }
            public class ItalianSwitzerlandCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("it-CH");
        }

        public string GetCultureCode(){
            return "it-CH";
        }
    }
            public class ItalianItalyCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("it-IT");
        }

        public string GetCultureCode(){
            return "it-IT";
        }
    }
            public class InuktitutSyllabicsCanadaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("iu-Cans-CA");
        }

        public string GetCultureCode(){
            return "iu-Cans-CA";
        }
    }
            public class InuktitutLatinCanadaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("iu-Latn-CA");
        }

        public string GetCultureCode(){
            return "iu-Latn-CA";
        }
    }
            public class JapaneseJapanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ja-JP");
        }

        public string GetCultureCode(){
            return "ja-JP";
        }
    }
            public class JavaneseIndonesiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("jv-Latn-ID");
        }

        public string GetCultureCode(){
            return "jv-Latn-ID";
        }
    }
            public class GeorgianGeorgiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ka-GE");
        }

        public string GetCultureCode(){
            return "ka-GE";
        }
    }
            public class KazakhKazakhstanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("kk-KZ");
        }

        public string GetCultureCode(){
            return "kk-KZ";
        }
    }
            public class GreenlandicGreenlandCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("kl-GL");
        }

        public string GetCultureCode(){
            return "kl-GL";
        }
    }
            public class KhmerCambodiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("km-KH");
        }

        public string GetCultureCode(){
            return "km-KH";
        }
    }
            public class KannadaIndiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("kn-IN");
        }

        public string GetCultureCode(){
            return "kn-IN";
        }
    }
            public class KoreanKoreaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ko-KR");
        }

        public string GetCultureCode(){
            return "ko-KR";
        }
    }
            public class KonkaniIndiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("kok-IN");
        }

        public string GetCultureCode(){
            return "kok-IN";
        }
    }
            public class CentralKurdishIraqCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ku-Arab-IQ");
        }

        public string GetCultureCode(){
            return "ku-Arab-IQ";
        }
    }
            public class KyrgyzKyrgyzstanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ky-KG");
        }

        public string GetCultureCode(){
            return "ky-KG";
        }
    }
            public class LuxembourgishLuxembourgCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("lb-LU");
        }

        public string GetCultureCode(){
            return "lb-LU";
        }
    }
            public class LaoLaoPDRCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("lo-LA");
        }

        public string GetCultureCode(){
            return "lo-LA";
        }
    }
            public class LithuanianLithuaniaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("lt-LT");
        }

        public string GetCultureCode(){
            return "lt-LT";
        }
    }
            public class LatvianLatviaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("lv-LV");
        }

        public string GetCultureCode(){
            return "lv-LV";
        }
    }
            public class MalagasyMadagascarCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("mg-MG");
        }

        public string GetCultureCode(){
            return "mg-MG";
        }
    }
            public class MaoriNewZealandCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("mi-NZ");
        }

        public string GetCultureCode(){
            return "mi-NZ";
        }
    }
            public class MacedonianFormerYugoslavRepublicofMacedoniaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("mk-MK");
        }

        public string GetCultureCode(){
            return "mk-MK";
        }
    }
            public class MalayalamIndiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ml-IN");
        }

        public string GetCultureCode(){
            return "ml-IN";
        }
    }
            public class MongolianCyrillicMongoliaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("mn-MN");
        }

        public string GetCultureCode(){
            return "mn-MN";
        }
    }
            public class MongolianTraditionalMongolianChinaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("mn-Mong-CN");
        }

        public string GetCultureCode(){
            return "mn-Mong-CN";
        }
    }
            public class MongolianTraditionalMongolianMongoliaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("mn-Mong-MN");
        }

        public string GetCultureCode(){
            return "mn-Mong-MN";
        }
    }
            public class MohawkMohawkCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("moh-CA");
        }

        public string GetCultureCode(){
            return "moh-CA";
        }
    }
            public class MarathiIndiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("mr-IN");
        }

        public string GetCultureCode(){
            return "mr-IN";
        }
    }
            public class MalayBruneiDarussalamCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ms-BN");
        }

        public string GetCultureCode(){
            return "ms-BN";
        }
    }
            public class MalayMalaysiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ms-MY");
        }

        public string GetCultureCode(){
            return "ms-MY";
        }
    }
            public class MalteseMaltaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("mt-MT");
        }

        public string GetCultureCode(){
            return "mt-MT";
        }
    }
            public class BurmeseMyanmarCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("my-MM");
        }

        public string GetCultureCode(){
            return "my-MM";
        }
    }
            public class NorwegianBokmålNorwayCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("nb-NO");
        }

        public string GetCultureCode(){
            return "nb-NO";
        }
    }
            public class NepaliIndiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ne-IN");
        }

        public string GetCultureCode(){
            return "ne-IN";
        }
    }
            public class NepaliNepalCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ne-NP");
        }

        public string GetCultureCode(){
            return "ne-NP";
        }
    }
            public class DutchBelgiumCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("nl-BE");
        }

        public string GetCultureCode(){
            return "nl-BE";
        }
    }
            public class DutchNetherlandsCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("nl-NL");
        }

        public string GetCultureCode(){
            return "nl-NL";
        }
    }
            public class NorwegianNynorskNorwayCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("nn-NO");
        }

        public string GetCultureCode(){
            return "nn-NO";
        }
    }
            public class NkoGuineaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("nqo-GN");
        }

        public string GetCultureCode(){
            return "nqo-GN";
        }
    }
            public class SesothosaLeboaSouthAfricaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("nso-ZA");
        }

        public string GetCultureCode(){
            return "nso-ZA";
        }
    }
            public class OccitanFranceCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("oc-FR");
        }

        public string GetCultureCode(){
            return "oc-FR";
        }
    }
            public class OromoEthiopiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("om-ET");
        }

        public string GetCultureCode(){
            return "om-ET";
        }
    }
            public class OdiaIndiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("or-IN");
        }

        public string GetCultureCode(){
            return "or-IN";
        }
    }
            public class PunjabiPakistanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("pa-Arab-PK");
        }

        public string GetCultureCode(){
            return "pa-Arab-PK";
        }
    }
            public class PunjabiIndiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("pa-IN");
        }

        public string GetCultureCode(){
            return "pa-IN";
        }
    }
            public class PolishPolandCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("pl-PL");
        }

        public string GetCultureCode(){
            return "pl-PL";
        }
    }
            public class DariAfghanistanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("prs-AF");
        }

        public string GetCultureCode(){
            return "prs-AF";
        }
    }
            public class PashtoAfghanistanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ps-AF");
        }

        public string GetCultureCode(){
            return "ps-AF";
        }
    }
            public class PortugueseAngolaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("pt-AO");
        }

        public string GetCultureCode(){
            return "pt-AO";
        }
    }
            public class PortugueseBrazilCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("pt-BR");
        }

        public string GetCultureCode(){
            return "pt-BR";
        }
    }
            public class PortuguesePortugalCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("pt-PT");
        }

        public string GetCultureCode(){
            return "pt-PT";
        }
    }
            public class KicheGuatemalaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("qut-GT");
        }

        public string GetCultureCode(){
            return "qut-GT";
        }
    }
            public class QuechuaBoliviaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("quz-BO");
        }

        public string GetCultureCode(){
            return "quz-BO";
        }
    }
            public class QuichuaEcuadorCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("quz-EC");
        }

        public string GetCultureCode(){
            return "quz-EC";
        }
    }
            public class QuechuaPeruCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("quz-PE");
        }

        public string GetCultureCode(){
            return "quz-PE";
        }
    }
            public class RomanshSwitzerlandCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("rm-CH");
        }

        public string GetCultureCode(){
            return "rm-CH";
        }
    }
            public class RomanianMoldovaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ro-MD");
        }

        public string GetCultureCode(){
            return "ro-MD";
        }
    }
            public class RomanianRomaniaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ro-RO");
        }

        public string GetCultureCode(){
            return "ro-RO";
        }
    }
            public class RussianRussiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ru-RU");
        }

        public string GetCultureCode(){
            return "ru-RU";
        }
    }
            public class KinyarwandaRwandaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("rw-RW");
        }

        public string GetCultureCode(){
            return "rw-RW";
        }
    }
            public class SanskritIndiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sa-IN");
        }

        public string GetCultureCode(){
            return "sa-IN";
        }
    }
            public class SakhaRussiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sah-RU");
        }

        public string GetCultureCode(){
            return "sah-RU";
        }
    }
            public class SindhiPakistanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sd-Arab-PK");
        }

        public string GetCultureCode(){
            return "sd-Arab-PK";
        }
    }
            public class SamiNorthernFinlandCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("se-FI");
        }

        public string GetCultureCode(){
            return "se-FI";
        }
    }
            public class SamiNorthernNorwayCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("se-NO");
        }

        public string GetCultureCode(){
            return "se-NO";
        }
    }
            public class SamiNorthernSwedenCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("se-SE");
        }

        public string GetCultureCode(){
            return "se-SE";
        }
    }
            public class SinhalaSriLankaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("si-LK");
        }

        public string GetCultureCode(){
            return "si-LK";
        }
    }
            public class SlovakSlovakiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sk-SK");
        }

        public string GetCultureCode(){
            return "sk-SK";
        }
    }
            public class SlovenianSloveniaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sl-SI");
        }

        public string GetCultureCode(){
            return "sl-SI";
        }
    }
            public class SamiSouthernNorwayCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sma-NO");
        }

        public string GetCultureCode(){
            return "sma-NO";
        }
    }
            public class SamiSouthernSwedenCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sma-SE");
        }

        public string GetCultureCode(){
            return "sma-SE";
        }
    }
            public class SamiLuleNorwayCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("smj-NO");
        }

        public string GetCultureCode(){
            return "smj-NO";
        }
    }
            public class SamiLuleSwedenCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("smj-SE");
        }

        public string GetCultureCode(){
            return "smj-SE";
        }
    }
            public class SamiInariFinlandCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("smn-FI");
        }

        public string GetCultureCode(){
            return "smn-FI";
        }
    }
            public class SamiSkoltFinlandCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sms-FI");
        }

        public string GetCultureCode(){
            return "sms-FI";
        }
    }
            public class ShonaLatinZimbabweCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sn-Latn-ZW");
        }

        public string GetCultureCode(){
            return "sn-Latn-ZW";
        }
    }
            public class SomaliSomaliaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("so-SO");
        }

        public string GetCultureCode(){
            return "so-SO";
        }
    }
            public class AlbanianAlbaniaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sq-AL");
        }

        public string GetCultureCode(){
            return "sq-AL";
        }
    }
            public class SerbianCyrillicBosniaandHerzegovinaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sr-Cyrl-BA");
        }

        public string GetCultureCode(){
            return "sr-Cyrl-BA";
        }
    }
            public class SerbianCyrillicSerbiaandMontenegroFormerCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sr-Cyrl-CS");
        }

        public string GetCultureCode(){
            return "sr-Cyrl-CS";
        }
    }
            public class SerbianCyrillicMontenegroCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sr-Cyrl-ME");
        }

        public string GetCultureCode(){
            return "sr-Cyrl-ME";
        }
    }
            public class SerbianCyrillicSerbiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sr-Cyrl-RS");
        }

        public string GetCultureCode(){
            return "sr-Cyrl-RS";
        }
    }
            public class SerbianLatinBosniaandHerzegovinaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sr-Latn-BA");
        }

        public string GetCultureCode(){
            return "sr-Latn-BA";
        }
    }
            public class SerbianLatinSerbiaandMontenegroFormerCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sr-Latn-CS");
        }

        public string GetCultureCode(){
            return "sr-Latn-CS";
        }
    }
            public class SerbianLatinMontenegroCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sr-Latn-ME");
        }

        public string GetCultureCode(){
            return "sr-Latn-ME";
        }
    }
            public class SerbianLatinSerbiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sr-Latn-RS");
        }

        public string GetCultureCode(){
            return "sr-Latn-RS";
        }
    }
            public class SouthernSothoSouthAfricaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("st-ZA");
        }

        public string GetCultureCode(){
            return "st-ZA";
        }
    }
            public class SwedishFinlandCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sv-FI");
        }

        public string GetCultureCode(){
            return "sv-FI";
        }
    }
            public class SwedishSwedenCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sv-SE");
        }

        public string GetCultureCode(){
            return "sv-SE";
        }
    }
            public class KiswahiliKenyaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("sw-KE");
        }

        public string GetCultureCode(){
            return "sw-KE";
        }
    }
            public class SyriacSyriaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("syr-SY");
        }

        public string GetCultureCode(){
            return "syr-SY";
        }
    }
            public class TamilIndiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ta-IN");
        }

        public string GetCultureCode(){
            return "ta-IN";
        }
    }
            public class TamilSriLankaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ta-LK");
        }

        public string GetCultureCode(){
            return "ta-LK";
        }
    }
            public class TeluguIndiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("te-IN");
        }

        public string GetCultureCode(){
            return "te-IN";
        }
    }
            public class TajikCyrillicTajikistanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("tg-Cyrl-TJ");
        }

        public string GetCultureCode(){
            return "tg-Cyrl-TJ";
        }
    }
            public class ThaiThailandCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("th-TH");
        }

        public string GetCultureCode(){
            return "th-TH";
        }
    }
            public class TigrinyaEritreaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ti-ER");
        }

        public string GetCultureCode(){
            return "ti-ER";
        }
    }
            public class TigrinyaEthiopiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ti-ET");
        }

        public string GetCultureCode(){
            return "ti-ET";
        }
    }
            public class TurkmenTurkmenistanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("tk-TM");
        }

        public string GetCultureCode(){
            return "tk-TM";
        }
    }
            public class SetswanaBotswanaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("tn-BW");
        }

        public string GetCultureCode(){
            return "tn-BW";
        }
    }
            public class SetswanaSouthAfricaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("tn-ZA");
        }

        public string GetCultureCode(){
            return "tn-ZA";
        }
    }
            public class TurkishTurkeyCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("tr-TR");
        }

        public string GetCultureCode(){
            return "tr-TR";
        }
    }
            public class TsongaSouthAfricaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ts-ZA");
        }

        public string GetCultureCode(){
            return "ts-ZA";
        }
    }
            public class TatarRussiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("tt-RU");
        }

        public string GetCultureCode(){
            return "tt-RU";
        }
    }
            public class CentralAtlasTamazightLatinAlgeriaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("tzm-Latn-DZ");
        }

        public string GetCultureCode(){
            return "tzm-Latn-DZ";
        }
    }
            public class CentralAtlasTamazightTifinaghMoroccoCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("tzm-Tfng-MA");
        }

        public string GetCultureCode(){
            return "tzm-Tfng-MA";
        }
    }
            public class UyghurChinaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ug-CN");
        }

        public string GetCultureCode(){
            return "ug-CN";
        }
    }
            public class UkrainianUkraineCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("uk-UA");
        }

        public string GetCultureCode(){
            return "uk-UA";
        }
    }
            public class UrduIndiaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ur-IN");
        }

        public string GetCultureCode(){
            return "ur-IN";
        }
    }
            public class UrduPakistanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("ur-PK");
        }

        public string GetCultureCode(){
            return "ur-PK";
        }
    }
            public class UzbekCyrillicUzbekistanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("uz-Cyrl-UZ");
        }

        public string GetCultureCode(){
            return "uz-Cyrl-UZ";
        }
    }
            public class UzbekLatinUzbekistanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("uz-Latn-UZ");
        }

        public string GetCultureCode(){
            return "uz-Latn-UZ";
        }
    }
            public class VietnameseVietnamCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("vi-VN");
        }

        public string GetCultureCode(){
            return "vi-VN";
        }
    }
            public class WolofSenegalCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("wo-SN");
        }

        public string GetCultureCode(){
            return "wo-SN";
        }
    }
            public class isiXhosaSouthAfricaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("xh-ZA");
        }

        public string GetCultureCode(){
            return "xh-ZA";
        }
    }
            public class YorubaNigeriaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("yo-NG");
        }

        public string GetCultureCode(){
            return "yo-NG";
        }
    }
            public class StandardMorrocanTamazightTifinaghMoroccoCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("zgh-Tfng-MA");
        }

        public string GetCultureCode(){
            return "zgh-Tfng-MA";
        }
    }
            public class ChineseSimplifiedChinaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("zh-CN");
        }

        public string GetCultureCode(){
            return "zh-CN";
        }
    }
            public class ChineseTraditionalHongKongSARCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("zh-HK");
        }

        public string GetCultureCode(){
            return "zh-HK";
        }
    }
            public class ChineseTraditionalMacaoSARCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("zh-MO");
        }

        public string GetCultureCode(){
            return "zh-MO";
        }
    }
            public class ChineseSimplifiedSingaporeCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("zh-SG");
        }

        public string GetCultureCode(){
            return "zh-SG";
        }
    }
            public class ChineseTraditionalTaiwanCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("zh-TW");
        }

        public string GetCultureCode(){
            return "zh-TW";
        }
    }
            public class isiZuluSouthAfricaCulture : IFormatCulture {
    
        public CultureInfo Culture() {
            return CultureInfo.CreateSpecificCulture("zu-ZA");
        }

        public string GetCultureCode(){
            return "zu-ZA";
        }
    }
    }